apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-go-basic-diyr
  namespace: e2e-demos-jgzn-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/test-images-protected@sha256:25f86f43f953b46cb846825ff457dfef9f2318d34741ee52d2e1fa020ea27efd
        name: my-go
        resources: {}
status: {}
